# Generated by Django 5.0.3 on 2024-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
