# Generated by Django 5.0.3 on 2024-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='bill',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
